theme: jekyll-theme-cayman

author: Phoenixthrush
title: "Phoenixthrush's Blog 🤍"
description: "A blog like every other"

social-network-links:
  email: "contact@phoenixthrush.com"
  github: Phoenixthrush

plugins:
  - jekyll-seo-tag
